### ISSUE TITLE
Validar campos para el registro, login, pass, edit.

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/api#12]
- [ ] First Name: 
     - El campo solo debe aceptar caracteres, no debe permitir numeros, espacio en blanco ni caracteres especiales.
     - Se debe validar el mínimo y máximo de caracteres permitido (minimo 3, maximo 15) 
- [ ] Last Name:
      - El campo solo debe aceptar caracteres, no debe permitir numeros, espacio en blanco ni caracteres especiales.
     - Se debe validar el mínimo y máximo de caracteres permitido (mínimo 3, máximo 15) 
- [ ] Email:
      - Debe ser único.
     - Debe validarse que sea un email válido.
- [ ] Password:
       - Se debe validar el mínimo y máximo de caracteres permitido para la contraseña (mínimo 6 máximo 12)
      - Se debe validar que la contraseña al menos acepte un caracter especial. ("seguridad")

**Comment by pamelagbl** [comment]
@alesanchezr aqui esta el issue, aunque dice para registro debe ser para login, recovery pass, para todo. Porque pedi un recovery pass y cuando lo hice no validó el min o max de caracteres para la contraseña (y eso fue web)

**Comment by alesanchezr** [comment]
@pamelagbl nadamas agregar:

- [ ] que tambien debe tener una mayuscula la contraseña.
- [ ] que el mail no puede ser mas grande q 150 caracteres.
