### ISSUE TITLE
The system allows expires Shifts

### ISSUE THREAD

**Issue by alacret** [JobCore/api#4]
The system shouldn't allow shifts with dates previous to today dates

**Comment by alesanchezr** [comment]
A que te refieres? El sistema no permite crear shifts con fechas anteriors a hoy. 

Seguramente encontraste ese shift asi porque paso la fecha de inicio y no hay ningun cronjob que lo marque como completado.

**Comment by alesanchezr** [comment]
closing this issue in favor of #7

**Comment by alacret** [comment]
@alesanchezr esto lo probe cuando arrancamos, si lo cambiaste entonces debe funcionar bien, si no, yo cree turnos que comenzaban en dias anteriores, y por eso no salian
